CC = gcc
CFLAGS = -Wall -g -Werror -std=c99

graph_tester: graph_tester.o graph.o minheap.o graph_algos.o
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $<

.PHONY: clean
clean:
	rm -f $(OBJ) graph_tester

.PHONY: help
help:
	@echo "usage: make [target]"
	@echo "all: executes program"
	@echo "clean: removes autogenerated files"